### ISSUE TITLE
import sha256 from 'crypto-js/sha256'; not working

### ISSUE THREAD

**Issue by durgaprasadmamidi** [udacity/nd1309_hashing#4]
**I am getting error like**

/home/codespace/workspace/nd1309_hashing/app.js:11
import sha256 from 'crypto-js/sha256';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by sirproton** [comment]
Same here too, because the project doesn't support ES6
use this instead

```
var SHA256 = require("crypto-js/sha256");

```
then
```
SHA256()
```

**Comment by Jur314** [comment]
works for me using import sha256 from 'crypto-js/sha256';
Maybe, add this in package.json 

`"type":"module"` 

then you could import sha256 module. For use it, just call it
`sha256(obj)`

**Comment by kenxlaw** [comment]
Yeah import not working for me using the original posters method. 2nd comment works but having trouble with running code.

**Comment by sreejithramesh** [comment]
I had the same issue and could not figure out. Changed the first line to the second and it started working.

//import sha256 from 'crypto-js/sha256';
const sha256 = require('crypto-js/sha256')

**Comment by priyanshisharma** [comment]
@kenxlaw along with the second comment, I changed `import sha256 from 'crypto-js/sha256';` to `import sha256 from 'crypto-js/sha256.js';` to make it work.

**Comment by RoHiT-engi** [comment]
> Same here too, because the project doesn't support ES6 use this instead
> 
> ```
> var SHA256 = require("crypto-js/sha256");
> ```
> 
> then
> 
> ```
> return SHA256()
> ```
